### PR TITLE
Require Composer Autoload

### PR DESCRIPTION
**Pull request by bernardodiasc**
This fix is necessary to work with Symphony 2.6.
Cheers.

### CODE REVIEW

**Comment by nitriques** [comment]
Yes but it breaks 2.5 compatibility... And I am not sure on how to deal with this.

The easiest thing would be to create version 2.0, making it only compatible with 2.6.

Or we could create code that check if the autoload file exists.

Maybe a `try... catch` would work ?

cc @brendo How did we (or should we) deal with this ?

**Comment by nitriques** [comment]
I've managed to make it compatible with 2.4 and 2.5 in 6e56c97c140230e9e28ca5384209d58c2b62d2a8

[Released in 1.4.0](https://github.com/symphonists/rest_api/releases/tag/1.4.0)

**Comment by bernardodiasc** [comment]
awesome! thanks man! :)

**Comment by nitriques** [comment]
:+1:

**Pull request merged**
